v = input('Digite algo: ')
print('O tipo primitivo do valor é:', type(v))
print('Só tem espaços?', v.isspace())
print('É um número ?', v.isnumeric())
print('É alfabéico?',  v.isalpha())
print('É um alfanumérico?', v.isalnum())
print('Esta em maiúsculas?', v.isupper())
print('Está em minúsculas?', v.islower())
print('Está capitalizada?', v.istitle())